# Generated by Django 5.2.8 on 2025-11-23 15:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32)),
                ('body', models.TextField()),
                ('from_number', models.CharField(help_text='Twilio WhatsApp number (e.g., whatsapp:+1415...)', max_length=32)),
                ('scheduled_time', models.DateTimeField(help_text='When to send the message')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('enqueued', 'Enqueued'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('result', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
